#!/usr/bin/env python3
"""
Generate deduplicated font glyphs for ESPHome configuration.

This script reads the ha-monitor.yaml file, extracts all icon substitutions,
deduplicates them, and generates a font-glyphs.yaml include file.

Run this script whenever you change icon substitutions in ha-monitor.yaml:
    python3 generate_font_glyphs.py
"""

import re


def extract_icon_substitutions(yaml_file):
    """Extract icon substitutions from the YAML file."""
    with open(yaml_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find all icon substitutions (pattern: r*c*_icon: "...")
    icon_pattern = r'r\d+c\d+_icon:\s*"([^"]+)"'
    icons = re.findall(icon_pattern, content)
    
    return icons


def deduplicate_icons(icons):
    """Remove duplicate icons while preserving order."""
    seen = set()
    unique_icons = []
    for icon in icons:
        if icon not in seen:
            seen.add(icon)
            unique_icons.append(icon)
    return unique_icons


def generate_glyphs_file(unique_icons, output_file):
    """Generate the font-glyphs.yaml include file."""
    glyphs_string = ''.join(unique_icons)
    
    content = f"""# This file is auto-generated by generate_font_glyphs.py
# DO NOT EDIT MANUALLY - Run 'python3 generate_font_glyphs.py' to regenerate

# Deduplicated icon glyphs
icon_glyphs: "{glyphs_string}"
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✓ Generated {output_file}")
    print(f"  Found {len(unique_icons)} unique icon(s)")
    if len(unique_icons) > 0:
        print(f"  Icons: {', '.join(repr(icon) for icon in unique_icons)}")


def main():
    yaml_file = 'ha-monitor.yaml'
    output_file = 'font-glyphs.yaml'
    
    print(f"Reading {yaml_file}...")
    icons = extract_icon_substitutions(yaml_file)
    
    if not icons:
        print("⚠ No icons found in substitutions!")
        print("  Make sure your YAML file contains icon substitutions like:")
        print('  r1c1_icon: "\\uea0b"')
        return
    
    print(f"Found {len(icons)} icon substitution(s)")
    unique_icons = deduplicate_icons(icons)
    
    generate_glyphs_file(unique_icons, output_file)
    print("\n✓ Done! You can now build your ESPHome configuration.")


if __name__ == '__main__':
    main()
