import { ConfigData } from '@/types/config';

export const defaultConfig: ConfigData = {
  deviceName: 'hamon',
  friendlyName: 'HAMon',
  hideClock: false,
  sensors: [
    {
      id: 'r1c1',
      type: 'sensor',
      entity: 'sensor.whole_home_energy_usage',
      label: 'Energy',
      icon: '\\uea0b',
      iconColor: '0xFFA500',
      format: '%.0fW',
      colorThreshHigh: '5000',
      colorThreshMid: '3000',
      colorThreshLow: '1000',
      colorHigh: '0xFF0000',
      colorMid: '0xFFA500',
      colorLow: '0x32CD32',
    },
    {
      id: 'r1c2',
      type: 'binary',
      entity: 'binary_sensor.front_door_sensor_contact',
      label: 'Front Door',
      stateOn: 'Open',
      stateOff: 'Closed',
      iconOn: '\\ueffc',
      iconOff: '\\ueffc',
      colorOn: '0xFF0000',
      colorOff: '0x32CD32',
    },
    {
      id: 'r2c1',
      type: 'sensor',
      entity: 'sensor.office_presence_one_temperature',
      label: 'Office',
      icon: '\\ue1ff',
      iconColor: '0x00BFFF',
      format: '%.1f°C',
      colorThreshHigh: '30',
      colorThreshMid: '25',
      colorThreshLow: '15',
      colorHigh: '0xFF0000',
      colorMid: '0xFFA500',
      colorLow: '0x32CD32',
    },
    {
      id: 'r2c2',
      type: 'switch',
      entity: 'switch.zigbee2mqtt_bridge_permit_join',
      label: 'Z2M Join',
      stateOn: 'On',
      stateOff: 'Off',
      iconOn: '\\ue8ac',
      iconOff: '\\ue8ac',
      colorOn: '0x4CAF50',
      colorOff: '0xFFFFFF',
    },
    {
      id: 'r3c1',
      type: 'binary',
      entity: 'binary_sensor.garden_pano_person_occupancy',
      label: 'Garden',
      stateOn: 'Detected',
      stateOff: 'Clear',
      iconOn: '\\ue7fd',
      iconOff: '\\ue7fd',
      colorOn: '0xFF0000',
      colorOff: '0x32CD32',
    },
    {
      id: 'r3c2',
      type: 'light',
      entity: 'light.kitchen_downlights',
      label: 'Kitchen',
      stateOn: 'On',
      stateOff: 'Off',
      iconOn: '\\ue0f0',
      iconOff: '\\ue0f0',
      colorOn: '0x000000',
      colorOff: '0xFFFFFF',
    },
    {
      id: 'r4c1',
      type: 'sensor',
      entity: 'sensor.downstairs_hallway_humidity',
      label: 'Humidity',
      icon: '\\uf87e',
      iconColor: '0x00BFFF',
      format: '%.0f%%',
      colorThreshHigh: '80',
      colorThreshMid: '60',
      colorThreshLow: '30',
      colorHigh: '0xFF0000',
      colorMid: '0xFFA500',
      colorLow: '0x32CD32',
    },
    {
      id: 'r4c2',
      type: 'binary',
      entity: 'binary_sensor.kitchen_entrance_motion_occupancy',
      label: 'Kitchen',
      stateOn: 'Detected',
      stateOff: 'Clear',
      iconOn: '\\uec10',
      iconOff: '\\uec10',
      colorOn: '0xFF0000',
      colorOff: '0x32CD32',
    },
  ],
};
