import { ConfigData } from '@/types/config';

export const defaultConfig: ConfigData = {
  deviceName: 'hamon',
  friendlyName: 'HAMon',
  sensors: [
    {
      id: 'r1c1',
      type: 'sensor',
      entity: 'sensor.whole_home_energy_usage',
      label: 'Energy',
      icon: '\\uea0b',
      iconColor: '0xFFA500',
      format: '%.0fW',
      colorThreshHigh: '5000',
      colorThreshMid: '3000',
      colorThreshLow: '1000',
      colorHigh: '0xFF0000',
      colorMid: '0xFFA500',
      colorLow: '0x32CD32',
    },
    {
      id: 'r1c2',
      type: 'binary',
      entity: 'binary_sensor.front_door_sensor_contact',
      label: 'Front Door',
      stateOn: 'Open',
      stateOff: 'Closed',
      iconOn: '\\ueffc',
      iconOff: '\\ue558',
      colorOn: '0xFF5252',
      colorOff: '0x32CD32',
    },
    {
      id: 'r2c1',
      type: 'sensor',
      entity: 'sensor.office_presence_one_temperature',
      label: 'Office',
      icon: '\\ue1ff',
      iconColor: '0x00BFFF',
      format: '%.1f°C',
      colorThreshHigh: '30',
      colorThreshMid: '25',
      colorThreshLow: '15',
      colorHigh: '0xFF0000',
      colorMid: '0xFFA500',
      colorLow: '0x32CD32',
    },
    {
      id: 'r2c2',
      type: 'binary',
      entity: 'binary_sensor.gate_door_contact',
      label: 'Gate',
      stateOn: 'Open',
      stateOff: 'Closed',
      iconOn: '\\ue559',
      iconOff: '\\ue558',
      colorOn: '0xFF5252',
      colorOff: '0x32CD32',
    },
    {
      id: 'r3c1',
      type: 'binary',
      entity: 'binary_sensor.garden_pano_person_occupancy',
      label: 'Garden',
      stateOn: 'Detected',
      stateOff: 'Clear',
      iconOn: '\\ue7fd',
      iconOff: '\\ue7fd',
      colorOn: '0xFF5252',
      colorOff: '0x32CD32',
    },
    {
      id: 'r3c2',
      type: 'binary',
      entity: 'binary_sensor.loft_access_door_contact',
      label: 'Loft',
      stateOn: 'Open',
      stateOff: 'Closed',
      iconOn: '\\ue88a',
      iconOff: '\\ue558',
      colorOn: '0xFF5252',
      colorOff: '0x32CD32',
    },
  ],
};
